SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') as PUBLISHED_DATE
FROM BOOK
# WHERE DATE_FORMAT(PUBLISHED_DATE, "%Y") = '2021' AND CATEGORY = '인문';
WHERE YEAR(PUBLISHED_DATE) = '2021' AND CATEGORY = '인문';